services:
  - type: web
    name: fairfetch-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fairfetch-postgres
          property: internalConnectionString
      - key: JWT_SECRET
        sync: false
      - key: FAIRFETCH_TOKEN_SECRET
        sync: false

databases:
  - name: fairfetch-postgres
